navigation_weight:
  Messaging: 1
  SMS: 1
  Voice: 2
  Verify: 3
  Number Insight: 4
  Account: 99
  Concepts: 0

  Overview: 1
  Developer Preview: 2
  Quickstarts: 3
  Guides: 4
  Building Blocks: 5

  Tutorials: 6
  API Reference: 7
  Conversation: 8

  Voice API: 1
  SIP: 2

  Client SDKs: 30
  NCCO Reference: 40
  SDK Documentation: 40
  API Reference: 50

  Getting Started: 2
  In-App Messaging: 3
  In-App Voice: 4

navigation_overrides:
  concepts:
    svg: 'mind-map'
    svgColor: 'red'
  messaging:
    svg: 'message'
    svgColor: 'purple'
  voice:
    svg: 'phone'
    svgColor: 'green'
  verify:
    svg: 'chat'
    svgColor: 'indigo'
  number-insight:
    svg: 'file-search'
    svgColor: 'orange'
  account:
    svg: 'user'
    svgColor: 'blue'
  stitch:
    svg: 'duplicate'
    svgColor: 'teal'
    label: 'Developer Preview'
    sdk-documentation:
      link: false
      prevent_navigation_item_class: true
      android:
        svg: 'open'
        svgColor: 'blue-dark'
      ios:
        svg: 'open'
        svgColor: 'blue-dark'
      javascript:
        svg: 'open'
        svgColor: 'blue-dark'
  messages-and-workflows-apis:
    svg: 'message'
    svgColor: 'purple'
    messages:
      label: 'Developer Preview'
    workflows:
      label: 'Developer Preview'
