title: "Nexmo Voice SDK Onboarding"

page:
  - row:
    - column:
      - type: header
        header:
          title:
            text: "Nexmo In-App Voice"
            align: center
          subtitle:
            text: "Nexmo In-App Voice includes all you need to build a feature-rich voice experience."
            align: center
          icon:
            name: "icon-star-full"
            color: "blue-dark"

  # - row:
  #   - column:
  #     - type: action_button
  #       action_button:
  #         text: "Generate Test Credentials"
  #         url: "/tutorials/client-sdk-generate-test-credentials"
  #         center_button: true

  - row:
    - column:
      - type: line_divider

  - row:
    - column:
      - type: header
        header:
          title:
            text: "Quickstart"
          icon: 
            name: "icon-check"
            color: "blue-dark"
          subtitle:
            text: "Use one of our tutorials to create an app from scratch to fit your use case."

  - row:
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-javascript-color"></use></svg>
              JavaScript
            </h2>
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Make Phone Calls with the JavaScript SDK](/tutorials/client-sdk-js-make-calls)"
              - item: "[Receive Phone Calls with the JavaScript SDK](/tutorials/client-sdk-js-receive-calls)"
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-android-color"></use></svg>
              Android
            </h2>
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Make and Receive Voice Calls with Android](/tutorials/client-sdk-android-make-receive-calls)"
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-apple-color"></use></svg>
              iOS
            </h2>
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Make Phone Calls with iOS](/tutorials/client-sdk-ios-outbound-pstn)"
              - item: "[Receive Phone Calls with iOS](/tutorials/client-sdk-ios-inbound-pstn)"
              - item: "[Make and Receive Voice Calls with iOS](/tutorials/client-sdk-ios-in-app-calling)"

  - row:
    - column:
        - type: line_divider

  - row:
    - column:
      - type: header
        header:
          title:
            text: "Integrate"
          icon: 
            name: "icon-fork"
            color: "blue-dark"
          subtitle:
            text: "Use one of our guides to integrate Nexmo into your existing app."

  - row:
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-javascript-color"></use></svg>
              JavaScript
            </h2>
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Add the Nexmo Client SDK to your JavaScript App](/tutorials/client-sdk-js-add-sdk-to-your-app)"
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-android-color"></use></svg>
              Android
            </h2>
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Add the Nexmo Client SDK to your Android App](/tutorials/client-sdk-android-add-sdk-to-your-app)"
    - column:
      - type: text
        text:
          content: |
            <h2 class="Vlt-title--icon">
              <svg class="Vlt-icon"><use xlink:href="/symbol/volta-brand-icons.svg#Brand-icon-apple-color"></use></svg>
              iOS
            </h2>
      - type: unordered_list
        unordered_list:
            bullet_shape: simple
            list:
              - item: "[Add the Nexmo Client SDK to your iOS App](/tutorials/client-sdk-ios-add-sdk-to-your-app)"